---
title: "Concordance Viewer"
resource_files:
- data/eliot_corpus.rds
- data/lawrence_corpus.rds
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(corpus)
library(dplyr)
library(here)
library(stringr)

lawrence_corpus <- here("data", "lawrence_corpus.rds") %>%
  readRDS() %>%
  mutate(
    title = as.character(book)
  )

eliot_corpus <- here("data", "eliot_corpus.rds") %>% 
  readRDS()

concordance <- function(corpus, search_term, left = -50, right = 50) {
  x <- corpus %>%
    corpus_frame() %>%
    text_locate(search_term) %>%
    mutate(
      before = as.character(before) %>% str_sub(start = left),
    instance = as.character(instance),
       after = as.character(after) %>% str_sub(end = right)
    )
  x$title <- corpus$title[as.numeric(x$text)]
  return(x %>% select(title, before, instance, after))
}

reactive_concordance <- reactive({
  input$goButton
  concordance(get(input$select), isolate(input$text))
})

instance_width <- reactive({
  input$goButton
  paste0(nchar(isolate(input$text))*10, 'px')
})
```

## Inputs {.sidebar}

### search

```{r}
selectInput(
  "select",
  label = "Select corpus", 
  choices =  list(
    "D. H. Lawrence" = "lawrence_corpus",
    "George Eliot" = "eliot_corpus"
  )
)
```

```{r}
textInput("text", label = "", value = "go away")
```

```{r}
actionButton("goButton", "Go!")
```

## Column {data-width=900}

### table

```{r table_viewer}
library(formattable)
library(DT)

renderDataTable({
  reactive_concordance() %>%
  select(before, node = instance, after, title) %>%
    formattable(
       align = c("r", "c", "l", "c"),
    list(`node` = formatter("span", style = ~ style(color = "#0071bc", font.weight = "bold")))) %>%
    as.datatable(
      filter = "top",
      escape = FALSE,
      options = list(
        pageLength = 500,
        columnDefs = list(
          list(className = 'dt-right', targets = 1),
          list(className = 'dt-center', targets = c(0, 2)),
          list(className = 'dt-left', targets = 3),
          list(width = instance_width(), targets = 2)
        )
      )
    )
})
```

